version: "3.4"

services:
  sshd:
    image: sshd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 20s
      update_config:
        order: start-first
      resources:
        limits:
          cpus: '0.25'
          memory: "64M"
    logging:
      options:
        max-size: "10M"
        max-file: "2"  
    ports:
      - "2222:22"
    environment:
      USER_KEYS_SYSOP: |-
        ssh-ed25519 [...] your name
#      HOST_PRIV_KEY_RSA: |-
#        -----BEGIN RSA PRIVATE KEY-----
#        paste your RSA host key here
#        -----END RSA PRIVATE KEY-----
#      HOST_PRIV_KEY_ED25519: |-
#        -----BEGIN OPENSSH PRIVATE KEY-----
#        paste your ED25519 host key here
#        -----END OPENSSH PRIVATE KEY-----
