variables:
  ALPINE_VERSION: "3.9"
  REVISION: "r1"

stages:
  - build

build:
  stage: build
  image: docker:18.06.1
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build
      --pull
      --build-arg ALPINE_VERSION="${ALPINE_VERSION}"
      -t $CI_REGISTRY_IMAGE:${ALPINE_VERSION}-${REVISION}
      .
    - docker tag $CI_REGISTRY_IMAGE:${ALPINE_VERSION}-${REVISION} $CI_REGISTRY_IMAGE:latest
#    - docker push $CI_REGISTRY_IMAGE
